// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    Explorer: typeof import('./src/view/Explorer.vue')['default']
    Favorite: typeof import('./src/view/Favorite.vue')['default']
    Info: typeof import('./src/view/Info.vue')['default']
    SelectList: typeof import('./src/component/SelectList.vue')['default']
    Splitter: typeof import('./src/component/Splitter.vue')['default']
  }
}
