// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    Column: typeof import('./src/view/explorer/Column.vue')['default']
    Explorer: typeof import('./src/view/explorer/Explorer.vue')['default']
    Favorite: typeof import('./src/view/Favorite.vue')['default']
    Info: typeof import('./src/view/Info.vue')['default']
  }
}
